// DtcElaboration.h — GENERATED from KLineKWP1281Lib_ESP32 fault_code_elaboration_EN.
// The fault info byte's low 7 bits select the elaboration (how it fails); bit7 = intermittent.
#pragma once
#include <cstdint>
namespace mmi {
static const char* const kElabTable[] = {
  /* 00 */ "-",
  /* 01 */ "Signal Shorted to Plus",
  /* 02 */ "Signal Shorted to Ground",
  /* 03 */ "No Signal",
  /* 04 */ "Mechanical Malfunction",
  /* 05 */ "Input Open",
  /* 06 */ "Signal too High",
  /* 07 */ "Signal too Low",
  /* 08 */ "Control Limit Surpassed",
  /* 09 */ "Adaptation Limit Surpassed",
  /* 0A */ "Adaptation Limit Not Reached",
  /* 0B */ "Control Limit Not Reached",
  /* 0C */ "Adaptation Limit (Mul) Exceeded",
  /* 0D */ "Adaptation Limit (Mul) Not Reached",
  /* 0E */ "Adaptation Limit (Add) Exceeded",
  /* 0F */ "Adaptation Limit (Add) Not Reached",
  /* 10 */ "Signal Outside Specifications",
  /* 11 */ "Control Difference",
  /* 12 */ "Upper Limit",
  /* 13 */ "Lower Limit",
  /* 14 */ "Malfunction in Basic Setting",
  /* 15 */ "Front Pressure Build-up Time too Long",
  /* 16 */ "Front Pressure Reducing Time too Long",
  /* 17 */ "Rear Pressure Build-up Time too Long",
  /* 18 */ "Rear Pressure Reducing Time too Long",
  /* 19 */ "Unknown Switch Condition",
  /* 1A */ "Output Open",
  /* 1B */ "Implausible Signal",
  /* 1C */ "Short to Plus",
  /* 1D */ "Short to Ground",
  /* 1E */ "Open or Short to Plus",
  /* 1F */ "Open or Short to Ground",
  /* 20 */ "Resistance Too High",
  /* 21 */ "Resistance Too Low",
  /* 22 */ "No Elaboration Available",
  /* 23 */ "-",
  /* 24 */ "Open Circuit",
  /* 25 */ "Faulty",
  /* 26 */ "Output won't Switch or Short to Plus",
  /* 27 */ "Output won't Switch or Short to Ground",
  /* 28 */ "Short to Another Output",
  /* 29 */ "Blocked or No Voltage",
  /* 2A */ "Speed Deviation too High",
  /* 2B */ "Closed",
  /* 2C */ "Short Circuit",
  /* 2D */ "Connector",
  /* 2E */ "Leaking",
  /* 2F */ "No Communications or Incorrectly Connected",
  /* 30 */ "Supply voltage",
  /* 31 */ "No Communications",
  /* 32 */ "Setting (Early) Not Reached",
  /* 33 */ "Setting (Late) Not Reached",
  /* 34 */ "Supply Voltage Too High",
  /* 35 */ "Supply Voltage Too Low",
  /* 36 */ "Incorrectly Equipped",
  /* 37 */ "Adaptation Not Successful",
  /* 38 */ "In Limp-Home Mode",
  /* 39 */ "Electric Circuit Failure",
  /* 3A */ "Can't Lock",
  /* 3B */ "Can't Unlock",
  /* 3C */ "Won't Safe",
  /* 3D */ "Won't De-Safe",
  /* 3E */ "No or Incorrect Adjustment",
  /* 3F */ "Temperature Shut-Down",
  /* 40 */ "Not Currently Testable",
  /* 41 */ "Unauthorized",
  /* 42 */ "Not Matched",
  /* 43 */ "Set-Point Not Reached",
  /* 44 */ "Cylinder 1",
  /* 45 */ "Cylinder 2",
  /* 46 */ "Cylinder 3",
  /* 47 */ "Cylinder 4",
  /* 48 */ "Cylinder 5",
  /* 49 */ "Cylinder 6",
  /* 4A */ "Cylinder 7",
  /* 4B */ "Cylinder 8",
  /* 4C */ "Terminal 30 missing",
  /* 4D */ "Internal Supply Voltage",
  /* 4E */ "Missing Messages",
  /* 4F */ "Please Check Fault Codes",
  /* 50 */ "Single-Wire Operation",
  /* 51 */ "Open",
  /* 52 */ "Activated",
};
inline const char* dtcElaboration(uint8_t info) {
  uint8_t code = info & 0x7F;
  if (code >= sizeof(kElabTable)/sizeof(kElabTable[0])) return nullptr;
  const char* s = kElabTable[code];
  return (s && s[0] && !(s[0]=='-' && s[1]==0)) ? s : nullptr;  // skip "-" placeholders
}
} // namespace mmi
